import '@/app/globals.css';
// import "../../../build.css"
import i18nConfig from "@/i18nConfig";
import { dir } from "i18next";
import { GoogleAnalytics } from "@next/third-parties/google";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: any;
  };
}>) {
  return (
    <html suppressHydrationWarning lang={locale} dir={dir(locale)}>
      <body>{children}</body>
      <GoogleAnalytics gaId="G-LMY7WXP3LK" />
  
    </html>
  )
}
